### ISSUE TITLE
Not able to run bing ads api downloader library

### ISSUE THREAD

**Issue by jatinrajani** [mara/bingads-performance-downloader#16]
When i run the library with parameters
--download-bingsads-performance-data \
--developer_token "abc" \ 
--oauth2_client_id "9#####" \
--oauth2_client_secret "r$$$" \
--oauth2_refresh_token "$$$" 
--data_dir /tmp/bingads

I am getting this syntax error:
 --download-bingsads-performance-data --developer_token "abc" \
                                                               ^
SyntaxError: invalid syntax

**Comment by martin-loetzsch** [comment]
I think you need to remove the `--` in front of `download-bingsads-performance-data`
