### ISSUE TITLE
Bing Ads API Version Changed to 13

### ISSUE THREAD

**Issue by flaviobritohelloprint** [mara/bingads-performance-downloader#17]
Bing Ads API version 12 sunset as of October 31, 2019. But still available since today when we received the following error:

   Code = "303"
                           Details = None
                           ErrorCode = "ApiVersionNoLongerSupported"
                           Message = "This version of the Microsoft Ads API is no longer supported. Please migrate to the latest version of the API. For more details, visit https://go.microsoft.com/fwlink/?linkid=862106."
                        }
                  }
Our current version depends on bingads==11.12.2

The page that you can find more information: [Version 13](https://docs.microsoft.com/en-us/advertising/ad-insight-service/ad-insight-service-reference?view=bingads-13)

**Comment by flaviobritohelloprint** [comment]
bingads.v12.reporting.reporting_service_manager import ReportingServiceManager, time
ModuleNotFoundError: No module named 'bingads.v12' if you try to update only the sdk. The code need to be changed

**Comment by martin-loetzsch** [comment]
fixed in https://github.com/mara/bingads-performance-downloader/pull/18
